# # Copyright VMware, Inc.
# # SPDX-License-Identifier: APACHE-2.0

# version: "2"

# services:
#   kafka:
#     container_name: i2p_node_kafka
#     image: docker.io/bitnami/kafka:3.7
#     ports:
#       - "19092:9092"
#     environment:
#       # KRaft settings
#       - KAFKA_CFG_NODE_ID=0
#       - KAFKA_CFG_PROCESS_ROLES=controller,broker
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#       # Listeners
#       - KAFKA_CFG_LISTENERS=EXTERNAL://localhost:9092,CONTROLLER://:9093
#       - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
#       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#       - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL
#   kafka-map:
#     container_name: i2p_node_kafka_map
#     image: dushixiang/kafka-map:latest
#     ports:
#       - "18080:8080"
#     environment:
#       - DEFAULT_USERNAME=admin
#       - DEFAULT_PASSWORD=admin
#   i2pd_node:
#     container_name: i2pd_node
#     image: chongrufan/i2pd_image:v8
#     # 需要修改暴露的端口
#     ports:
#       - "32153:32153"
#       - "32154:32154"
#       - "32155:32155"
#       - "32156:32156"
#     volumes:
#       - "/root/i2pd_test/config.ini:/app/mycode/config.ini"
#       - "/root:/root"
#     privileged: true